title: '8428695'
description: Para kazandır beni lütfen türkçe yayın yabancı dil yok
template:
  repo: 8428695-template
  name: '8428695'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
